### ISSUE TITLE
How I can change the question 

### ISSUE THREAD

**Issue by veto111** [JavonDavis/Chatwa#2]
Can you post screenshot from your database from firebase

**Comment by JavonDavis** [comment]
<img width="498" alt="screen shot 2017-08-01 at 11 21 15 am" src="https://user-images.githubusercontent.com/6520461/28835615-9c50010c-76ab-11e7-9025-8f43ac0a1cc7.png">

The model resembles something like that at the moment, where 'words' is a top level node. However, you cannot write to the firebase model at the moment. The plan is to create a portal for revisions and new words to be submitted but haven't found the time really. If you'd like to change a question or hint then open an issue with it and I'll respond there and make the change manually if appropriate. Thanks
