### ISSUE TITLE
Chatwa

### ISSUE THREAD

**Issue by veto111** [JavonDavis/Chatwa#3]
Hi 

I wondering how I can add new question  and answer in the firebase because the database I can't do same as your post pic  and the rules on firebase database like this one {
  "rules": {
    ".read": "true",
    ".write": "true"
  }
}   if not correct plz corrected when u corrected  I can  make question 

thank you

**Comment by JavonDavis** [comment]
Please read carefully what I said in #2. For security reasons, anyone cannot just write to the database, this is the live database that the app is using and as such, I need to regulate how questions get added to the database as to not break the app. If you have a question you would like to add, please post the details of it in an issue. I will review and manually add it to the Firebase database myself.

**Comment by veto111** [comment]
thank you

**Comment by veto111** [comment]
but I mean if I need prepare my own  database and use it as new project from Xcode 
I was ask you how the  database  style will be come
